### ISSUE TITLE
Tooltip flicker in Ribbon Elements that are inside menu/dropdown

### ISSUE THREAD

**Issue by SebiCiuca** [dotnet/wpf#6220]
* .NET Core Version: 6.0.101
* Windows version: 21H1 OS Build : 19043.1526
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
 In .NET6 if you have a tooltip on a combobox/menu item it flickers and can't be read by user ( see picture https://imgur.com/a/RxFvAPP )
 **Actual behavior:** 
 Tooltip shows for just a few milliseconds on the screen and closes itself.
 **Expected behavior:**
 Tooltip does not close itself unless user moves the mouse
 **Minimal repro:**
https://github.com/SebiCiuca/RibbonToolTipFlicker

Steps to reproduce:
Open app .NET 5 - all tooltips for RibbonButton/RibbonMenuItem/RibbonGallery can be read by user ( they do not close unless move move)
Open app .NET 6 - tooltip from RibbonMenuItem/RibbonGallery can't be read by user they close in a matter of milliseconds. RibbonButton tooltip still works

**Comment by lindexi** [comment]
See https://github.com/dotnet/wpf/issues/5870 https://github.com/dotnet/wpf/issues/4612 https://github.com/dotnet/wpf/issues/5703 https://github.com/dotnet/wpf/issues/5716

**Comment by YerongAI** [comment]
> See #5870 #4612 #5703 #5716
> 
> Could you try dotnet 6.0.2 version?

I have tried .NET Runtime 6.0.3 and complied with .NET SDK 6.0.201, the problem still not fixed.

Just simply add more items to ComboBox, the first item may work, but the others may not work.

**Comment by YerongAI** [comment]
> > See #5870 #4612 #5703 #5716
> > Could you try dotnet 6.0.2 version?
> 
> I have tried .NET Runtime 6.0.3 and complied with .NET SDK 6.0.201, the problem still not fixed.
> 
> Just simply add more items to ComboBox, the first item may work, but the others may not work.

```xaml
  <ComboBox HorizontalAlignment="Center" VerticalAlignment="Center">
      <ComboBoxItem Content="1" ToolTip="1"/>
      <ComboBoxItem Content="2" ToolTip="2"/>
      <ComboBoxItem Content="3" ToolTip="3"/>
      <ComboBoxItem Content="4" ToolTip="4"/>
      <ComboBoxItem Content="5" ToolTip="5"/>
      <ComboBoxItem Content="6" ToolTip="6"/>
  </ComboBox>
```

Test result: 1 and 2 worked, others not.

**Comment by YerongAI** [comment]
> > > See #5870 #4612 #5703 #5716
> > > Could you try dotnet 6.0.2 version?
> > 
> > 
> > I have tried .NET Runtime 6.0.3 and complied with .NET SDK 6.0.201, the problem still not fixed.
> > Just simply add more items to ComboBox, the first item may work, but the others may not work.
> 
> ```
>   <ComboBox HorizontalAlignment="Center" VerticalAlignment="Center">
>       <ComboBoxItem Content="1" ToolTip="1"/>
>       <ComboBoxItem Content="2" ToolTip="2"/>
>       <ComboBoxItem Content="3" ToolTip="3"/>
>       <ComboBoxItem Content="4" ToolTip="4"/>
>       <ComboBoxItem Content="5" ToolTip="5"/>
>       <ComboBoxItem Content="6" ToolTip="6"/>
>   </ComboBox>
> ```
> 
> Test result: 1 and 2 worked, others not.

More info: This problem occurs only on non-100% scaling.

**Comment by OptimaDan** [comment]
This problem does not just affect ComboBox. It seems to affect all controls.

Another example:
`<Grid ToolTip="Flash" Background="Red" Height="100"/>`

I have Windows 11 Pro (22000.556) with a 4K monitor. The tooltip flash issue only occurs when I set the display scale to 150% or more.

.NET 5.0 works fine. It's only an issue with .NET 6.0.3

**Comment by ryoasai** [comment]
OptimaDan's comment is true. I also found that this bug affects all controls.

You can reproduce it even with the simplest possible WPF app generated from template!
I also use 4k display and 175% scaling.
I think this is a major regression since 6.0.3 and it should be fixed in higher priority.

```
<Grid>
        <Button ToolTip="Hello World"  Content="Button"  VerticalAlignment="Top"/>
</Grid>

```

**Comment by ryoasai** [comment]
I installed the previous SDK and put global.json but the problem still persists.
Is this caused by windows update rather than dotnet update?



```
{
  "sdk": {
    "version": "6.0.200"
  }
}
```

Windows10(21H2) 
install date 2021/02/02
os build 19044.1586

**Comment by Rand-Random** [comment]
@ryoasai 
It is caused by the runtime in which .net version your application is running and not with which sdk you are working/building.

you can check which runtime your application is using by calling this in your app.
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.frameworkdescription?view=net-6.0

To force a different runtime, I believe the only way is to switch from framework dependent to self contained.
https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained

In self contained you can specify the runtime yourself

**Comment by redseujac75** [comment]
> To force a different runtime, I believe the only way is to switch from framework dependent to self contained. https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained
> 
> In self contained you can specify the runtime yourself

Is it possible to specify a specific runtime (sub)version, e.g. "net6.0.2" ?  I'm afraid this will not work. The parameters "-f net5.0" or "-f net6.0" should work on the other hand, but that does not resolve the problem with the Windows Desktop Runtime 6.0.3.

**Comment by Rand-Random** [comment]
@redseujac75 
As I already said, I believe that is impossible when you are using the framework dependent app model.
Because you are "dependent" on the "framework" that is installed on the client machine.

With "-f" you are only specifing the minimum framework you are supporting eg. saying ".net6.0" means you are supporting anything on ".net6.0.x".

This is so that when a new hotfix release comes eg. .net6.0.1, and your clients installs this update either manually or through windows update, you don't have to rebuild your app and each and every client that has the app would need to re-install it.

You don't need to lift a finger and your app automatically gets all the fixes that came with .net6.0.1.

This is the desired output because normally the fixes with a hotfix release are good, and shouldn't cause issues.

There are now 3 possible ways to fix this
1. uninstall the runtime that causes the issue and go back the old one
2. pick up a stick and hit the person who introduced the bug with that stick so long untill the bug gets fixed and a new runtime gets released
3. remove the "framework dependency" by switching your app model to "self-contained", with "self-contained" it doesn't matter what runtime is installed on the clients machine because your app will run on that runtime you deliever with your app, the "whole" runtime is bundeld with your app and you are in full control when you update the runtime and when not

Everything I wrote is to my best of knowledge.

**Comment by redseujac75** [comment]
Thank you. But with "self-contained" you unfortunately also deliver actually the damned runtime 6.0.3 which is on the developer computer :(

It's also rather problematic to uninstall the runtime 6.0.3 because it has been installed within the most recent Visual Studio 2022 update :(

So finally what I wanted to explain is that it isn't that easy to specify the runtime yourself in self-contained in the given actual circumstances. So, indeed we will have to hit the person who introduced the bug :)

A final remark: updates for .NET Desktop Runtimes are normally never included in Windows Updates.

**Comment by Rand-Random** [comment]
@redseujac75 
> It's also rather problematic to uninstall the runtime 6.0.3 because it has been installed within the most recent Visual Studio 2022 update :(

Why would it be problematic? 

----

> Thank you. But with "self-contained" you unfortunately also deliver actually the damned runtime 6.0.3 which is on the developer computer :(

You can change it with a global.json

```
{
  "sdk": {
    "version": "6.0.200"
  }
}
```

![image](https://user-images.githubusercontent.com/9868626/158031470-0eb8ac0e-2087-4953-a309-85e9d8ce966f.png)

This app with display .NET 6.0.2 with running the ConsoleApp1.exe from the publish folder because there it is configured as self-contained, but from bin/debug it will display .NET 6.0.3 as it is running with the latest .net 6.0.x version that is installed on the machine.

----

> A final remark: updates for .NET Desktop Runtimes are normally never included in Windows Updates.

That seems to be incorrect, as you can see here, unless you actually meant the difference between Windows Update and Microsoft Update:
https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/

> What will be delivered from MU?
Updates with both security and non-security fixes for all supported versions of .NET Core (currently .NET Core 2.1, .NET Core 3.1 and .NET 5.0) will be available on MU. These updates will target the .NET Core SDK, .NET Core Runtime, ASP.NET Core Runtime, and the .NET Core Desktop Runtime installers deployed either independently or as part of another application. .NET Core runtime binaries included with an application built as a self-contained deployment will not be updated by MU.

----

**Comment by redseujac75** [comment]
Thank you very much for your great answer!

With adding a global.json file and publishing "self-contained" it didn't work for my project (Windows Desktop app - C# WPF). I don't know why.

Meanwhile I also found the [https://docs.microsoft.com/en-us/dotnet/core/versions/selection](url)  and added
`<RuntimeFrameworkVersion>6.0.2</RuntimeFrameworkVersion>`   to my project file. Now it's working with "self-contained" :)

**Comment by redseujac75** [comment]
Let's hope that this .NET 6 WPF Tooltip bug can and will be fixed soon! I wonder if the .NET 6 team is reading all this?

**Comment by nnguyetnam** [comment]
yes, it is a problem on our production code now.
we have used heavily "the Tooltip" until .Net 5 and now it is broken on .Net 6
Please help to consider it is high-priority issue

**Comment by redseujac75** [comment]
> @redseujac75
> 
> > It's also rather problematic to uninstall the runtime 6.0.3 because it has been installed within the most recent Visual Studio 2022 update :(
> 
> Why would it be problematic?
> 
Because it has been installed/included with the latest Visual Studio Community 2022 update.  So, I do not know how to uninstall it separately (without touching Visual Studio).

**Comment by SamBent** [comment]
There is a lot of confusing and sometimes inaccurate information in this issue and related issues.  I will try to clarify.

* .NET 6.0 included new tooltip behavior, to meet global accessibility standards (WCAG 2.1).
* This broke tooltips in ComboBox (and other popups):  the tooltips would close immediately.  This was first reported in #5716.
* This was fixed in .NET 7.0, and backported to .NET 6.0.3.  Sadly the fix broke all tooltips in high-DPI (display scaled to greater than 100%).  The symptom is the same (the tooltips close immediately), but it's really a different bug.
* This was first reported in this issue ([YerongAl's comment](https://github.com/dotnet/wpf/issues/6220#issuecomment-1062520643)), although the connection to high-DPI wasn't recognized until later.
* It was reported at least twice more, in #6283 and #6289.  These are all the same bug.
* The OP @SebiCiuca was using 6.0.1, hence was seeing #5716.  Later commenters saw "the same problem" in 6.0.3, but it's really a different problem (albeit with the same symptom).
* The high-DPI problem doesn't actually affect all tooltips.  Rather, it depends on the scaling and on the distance between the mouse and the origin of the surrounding window.  The code closes the tooltip when the mouse is not within a certain region;  the bug is that the code uses scaled coordinates for the mouse, but unscaled coordinates for the region.  If the mouse is close to the origin, the coordinates are more likely to be close enough to pass the containment test.  This explains remarks like "the first item may work, but the others may not work", as well the behavior of @SebiCiuca's repro (in 6.0.3) where some of the tooltips work better than others.
* @ThomasGoulet73 proposed PR #6300 to fix the issue, but I have a better fix that uses fewer transforms and multiplications.  I expect to have a PR very soon, and surely in time to include in the next servicing window (I think that's 6.0.5 - the payload for 6.0.4 was already locked before any of these reports reached us).

**Comment by Rand-Random** [comment]
@singhashish-wpf 
Does the merge actually fix the original issue?
Notice that the conversation in this topic shifted to a different issue.

**Comment by singhashish-wpf** [comment]
> @singhashish-wpf Does the merge actually fix the original issue? Notice that the conversation in this topic shifted to a different issue.

The merged PR will fix the tooltip getting closed immediately in high DPI scenarios.

**Comment by DanStevens** [comment]
Is there a way to downgrade .NET to 6.0.2 until this issue is properly fixed?

**Comment by Ray-Wynn** [comment]
The issue is related to scale settings other than 100% (merged report #6336) on Windows 11. 
System -> Display -> Scale = 100% problem disappears. 
If this helps getting it fixed sooner?

**Comment by RajeshAKumar** [comment]
This is breaking production system and we can't dictate to end users how they should use the windows scaling.....

Can we expect a patch sooner than 6.05?
Please consider this a high priority.

**Comment by ThomasGoulet73** [comment]
@RajeshAKumar .Net 6.0.5 is the next servicing release so it probably can't be sooner than .Net 6.0.5. The current servicing release for April is .Net 6.0.4 so you can expect .Net 6.0.5 to be released next month.

**Comment by RajeshAKumar** [comment]
> 

Sure if it is within a month, that is great. Thank you.

**Comment by johnco3** [comment]
I encountered this flashing tooltips also.  It really affects my workflow as the viewing IDE at 100% makes the tiny fonts on the menus almost impossible to read.  I wasted 2 days tracking this bug down (reinstalling windows and Visual Studio and trying on various other PCs).  I wish I saw this discussion last week :(  Surely ms can push this .Net update a little earlier than usual (before I go blind!).

**Comment by Rand-Random** [comment]
FYI - 6.0.5 got released
https://devblogs.microsoft.com/dotnet/may-2022-updates/

**Comment by RajeshAKumar** [comment]
Thank you for notifying about the release!
This is really good and I could verify that it works fine for our products.

**Comment by laurentkempe** [comment]
6.0.5 also fixes the issue I had with tooltip 👍🏼 !

**Comment by singhashish-wpf** [comment]
Thank you all for testing and confirming the fix.
