### ISSUE TITLE
VB WPF .NET Core 3.0 missing from New Project dialog

### ISSUE THREAD

**Issue by chrisforte** [dotnet/wpf#667]
I have the ability to create a new C# WPF .NET core project, but not a Visual Basic project. 

(Using Visual Studio 2019 latest preview and .NET core 3.0 preview 5)

/cc @rladuca

**Comment by Berrysoft** [comment]
I've added the template for `dotnet new` in #538, and it will be available in preview 6. But I don't know where to add a Visual Studio template.

**Comment by grubioe** [comment]
Addressed by PR #538

**Comment by vatsan-madhavan** [comment]
@BerrySoft, I suspect that the missing piece is under https://github.com/dotnet/templates/tree/master/src/Templates/DotnetCore

**Comment by Berrysoft** [comment]
@vatsan-madhavan Thanks. It seems that the template has been added.😁

**Comment by reduckted** [comment]
> @Berrysoft  It seems that the template has been added.😁

Am I missing something, or is the template still not available in Visual Studio 2019? It's not appearing in the New Project dialog, and `dotnet new` doesn't list a VB template for any WPF projects. 😕 

**.NET CLI**
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Visual Studio**
```
Microsoft Visual Studio Professional 2019
Version 16.3.5
VisualStudio.16.Release/16.3.5+29411.108
Microsoft .NET Framework
Version 4.8.03761
```

**`dotnet new`**
```
Templates                                         Short Name               Language          Tags                                 
----------------------------------------------------------------------------------------------------------------------------------
Console Application                               console                  [C#], F#, VB      Common/Console                       
Class library                                     classlib                 [C#], F#, VB      Common/Library                       
WPF Application                                   wpf                      [C#]              Common/WPF                           
WPF Class library                                 wpflib                   [C#]              Common/WPF                           
WPF Custom Control Library                        wpfcustomcontrollib      [C#]              Common/WPF                           
WPF User Control Library                          wpfusercontrollib        [C#]              Common/WPF                           
Windows Forms (WinForms) Application              winforms                 [C#]              Common/WinForms                      
...<snip>...
```

Is there something that I've forgotten to install?

**Comment by Berrysoft** [comment]
> @reduckted  Is there something that I've forgotten to install?

No. The VB template was removed from .NET Core 3.0 SDK in #1735 because of #1734 .

**Comment by reduckted** [comment]
Well that's disappointing. I've just manually created a .NET Core WPF project and it's functioning quite well, so I'm not sure what the problems could be. But this isn't really the place to discuss that ¯\\\_(ツ)_/¯

Thanks for pointing that out though 😄 👍

**Comment by vatsan-madhavan** [comment]
@reduckted try using a daily build of the .NET 5 SDK from [dotnet/core-sdk](https://github.com/dotnet/core-sdk)
